layout_spectrum: 0.3436595
typography_spectrum: 0.4543497
color:
  saturation: 0.2927372
  lightness: 0.3162717
  brandStrength: 0.890493
  rhythmicContrast: 0.2752942
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Vessels of Water
